### ISSUE TITLE
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set

### ISSUE THREAD

**Issue by taoquanqing** [jhbastek/VideoMetamaterials#5]
I run this project with GTX4090 and I9-14900k.
When I launch the  'accelerate launch main.py,' it gives the error as follows.
```
Traceback (most recent call last):
  File "D:\4D_printing_inverse_design\VideoMetamaterials_1.0.0\main.py", line 121, in <module>
    main()
  File "D:\4D_printing_inverse_design\VideoMetamaterials_1.0.0\main.py", line 31, in main
    dist.init_process_group(backend='gloo')
  File "C:\Users\user\.conda\envs\vediometa\Lib\site-packages\torch\distributed\c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.conda\envs\vediometa\Lib\site-packages\torch\distributed\distributed_c10d.py", line 1141, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.conda\envs\vediometa\Lib\site-packages\torch\distributed\rendezvous.py", line 231, in _env_rendezvous_handler
    rank = int(_get_env_or_raise("RANK"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.conda\envs\vediometa\Lib\site-packages\torch\distributed\rendezvous.py", line 216, in _get_env_or_raise
    raise _env_error(env_var)
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\.conda\envs\vediometa\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\.conda\envs\vediometa\Lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "C:\Users\user\.conda\envs\vediometa\Lib\site-packages\accelerate\commands\launch.py", line 1174, in launch_command
    simple_launcher(args)
  File "C:\Users\user\.conda\envs\vediometa\Lib\site-packages\accelerate\commands\launch.py", line 769, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\user\\.conda\\envs\\vediometa\\python.exe', 'main.py']' returned non-zero exit status 1.
```
The **accelerate config** is 
```
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: 'NO'
downcast_bf16: 'no'
enable_cpu_affinity: false
gpu_ids: '0'
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
I am wondering how to change the configuration or code to run the file. Thank you for your excellent work!

**Comment by taoquanqing** [comment]
```
# Remove distributed process group initialization
# dist.init_process_group(backend='gloo')  # No need for this in single GPU setup

# Remove DistributedDataParallelKwargs and InitProcessGroupKwargs
# ddp_kwargs = DistributedDataParallelKwargs(find_unused_parameters=True)
# ip_kwargs = InitProcessGroupKwargs(timeout=datetime.timedelta(seconds=60*10))

# Initialize Accelerator with mixed precision, no kwargs_handlers needed for single GPU
accelerator = Accelerator(mixed_precision='fp16', log_with='wandb' if wandb_username is not None else None)

# Use `accelerator` in your training loop
```
It was solved by modifying the main.py as above.
